# Generated by Django 6.0.3 on 2026-03-06 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("recipients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(choices=[("email", "Email"), ("sms", "SMS")], max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipients",
                    models.ManyToManyField(related_name="rules", to="recipients.recipient"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
